
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  CSProtocol.bond
//   Output filename: CSProtocol_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace CommonSchema
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Ingest
    {
        [global::Bond.Id(1), global::Bond.Required]
        public long time { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string clientIp { get; set; }

        [global::Bond.Id(3)]
        public long auth { get; set; }

        [global::Bond.Id(4)]
        public long quality { get; set; }

        [global::Bond.Id(5)]
        public long uploadTime { get; set; }

        [global::Bond.Id(6)]
        public string userAgent { get; set; }

        [global::Bond.Id(7)]
        public string client { get; set; }

        public Ingest()
            : this("CommonSchema.Ingest", "Ingest")
        {}

        protected Ingest(string fullName, string name)
        {
            clientIp = "";
            userAgent = "";
            client = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class User
    {
        [global::Bond.Id(1)]
        public string id { get; set; }

        [global::Bond.Id(2)]
        public string localId { get; set; }

        [global::Bond.Id(3)]
        public string authId { get; set; }

        [global::Bond.Id(4)]
        public string locale { get; set; }

        public User()
            : this("CommonSchema.User", "User")
        {}

        protected User(string fullName, string name)
        {
            id = "";
            localId = "";
            authId = "";
            locale = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Loc
    {
        [global::Bond.Id(1)]
        public string id { get; set; }

        [global::Bond.Id(2)]
        public string country { get; set; }

        [global::Bond.Id(3)]
        public string timezone { get; set; }

        public Loc()
            : this("CommonSchema.Loc", "Loc")
        {}

        protected Loc(string fullName, string name)
        {
            id = "";
            country = "";
            timezone = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Device
    {
        [global::Bond.Id(1)]
        public string id { get; set; }

        [global::Bond.Id(2)]
        public string localId { get; set; }

        [global::Bond.Id(3)]
        public string authId { get; set; }

        [global::Bond.Id(4)]
        public string authSecId { get; set; }

        [global::Bond.Id(5)]
        public string deviceClass { get; set; }

        [global::Bond.Id(6)]
        public string orgId { get; set; }

        [global::Bond.Id(7)]
        public string orgAuthId { get; set; }

        [global::Bond.Id(8)]
        public string make { get; set; }

        [global::Bond.Id(9)]
        public string model { get; set; }

        public Device()
            : this("CommonSchema.Device", "Device")
        {}

        protected Device(string fullName, string name)
        {
            id = "";
            localId = "";
            authId = "";
            authSecId = "";
            deviceClass = "";
            orgId = "";
            orgAuthId = "";
            make = "";
            model = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Os
    {
        [global::Bond.Id(1)]
        public string locale { get; set; }

        [global::Bond.Id(2)]
        public string expId { get; set; }

        [global::Bond.Id(3)]
        public int bootId { get; set; }

        [global::Bond.Id(4)]
        public string name { get; set; }

        [global::Bond.Id(5)]
        public string ver { get; set; }

        public Os()
            : this("CommonSchema.Os", "Os")
        {}

        protected Os(string fullName, string name)
        {
            locale = "";
            expId = "";
            this.name = "";
            ver = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class App
    {
        [global::Bond.Id(1)]
        public string expId { get; set; }

        [global::Bond.Id(2)]
        public string userId { get; set; }

        [global::Bond.Id(3)]
        public string env { get; set; }

        [global::Bond.Id(4)]
        public int asId { get; set; }

        [global::Bond.Id(5)]
        public string id { get; set; }

        [global::Bond.Id(6)]
        public string ver { get; set; }

        [global::Bond.Id(7)]
        public string locale { get; set; }

        [global::Bond.Id(8)]
        public string name { get; set; }

        public App()
            : this("CommonSchema.App", "App")
        {}

        protected App(string fullName, string name)
        {
            expId = "";
            userId = "";
            env = "";
            id = "";
            ver = "";
            locale = "";
            this.name = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Utc
    {
        [global::Bond.Id(1)]
        public string stId { get; set; }

        [global::Bond.Id(2)]
        public string aId { get; set; }

        [global::Bond.Id(3)]
        public string raId { get; set; }

        [global::Bond.Id(4)]
        public string op { get; set; }

        [global::Bond.Id(5)]
        public long cat { get; set; }

        [global::Bond.Id(6)]
        public long flags { get; set; }

        [global::Bond.Id(7)]
        public string sqmId { get; set; }

        [global::Bond.Id(9)]
        public string mon { get; set; }

        [global::Bond.Id(10)]
        public int cpId { get; set; }

        [global::Bond.Id(11)]
        public string bSeq { get; set; }

        [global::Bond.Id(12)]
        public string epoch { get; set; }

        [global::Bond.Id(13)]
        public long seq { get; set; }

        [global::Bond.Id(14)]
        public double popSample { get; set; }

        [global::Bond.Id(15)]
        public long eventFlags { get; set; }

        public Utc()
            : this("CommonSchema.Utc", "Utc")
        {}

        protected Utc(string fullName, string name)
        {
            stId = "";
            aId = "";
            raId = "";
            op = "";
            sqmId = "";
            mon = "";
            bSeq = "";
            epoch = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class M365a
    {
        [global::Bond.Id(1)]
        public string enrolledTenantId { get; set; }

        public M365a()
            : this("CommonSchema.M365a", "M365a")
        {}

        protected M365a(string fullName, string name)
        {
            enrolledTenantId = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Xbl
    {
        [global::Bond.Id(5)]
        public Dictionary<string, string> claims { get; set; }

        [global::Bond.Id(10)]
        public string nbf { get; set; }

        [global::Bond.Id(20)]
        public string exp { get; set; }

        [global::Bond.Id(30)]
        public string sbx { get; set; }

        [global::Bond.Id(40)]
        public string dty { get; set; }

        [global::Bond.Id(50)]
        public string did { get; set; }

        [global::Bond.Id(60)]
        public string xid { get; set; }

        [global::Bond.Id(70)]
        public ulong uts { get; set; }

        [global::Bond.Id(80)]
        public string pid { get; set; }

        [global::Bond.Id(90)]
        public string dvr { get; set; }

        [global::Bond.Id(100)]
        public uint tid { get; set; }

        [global::Bond.Id(110)]
        public string tvr { get; set; }

        [global::Bond.Id(120)]
        public string sty { get; set; }

        [global::Bond.Id(130)]
        public string sid { get; set; }

        [global::Bond.Id(140)]
        public long eid { get; set; }

        [global::Bond.Id(150)]
        public string ip { get; set; }

        public Xbl()
            : this("CommonSchema.Xbl", "Xbl")
        {}

        protected Xbl(string fullName, string name)
        {
            claims = new Dictionary<string, string>();
            nbf = "";
            exp = "";
            sbx = "";
            dty = "";
            did = "";
            xid = "";
            pid = "";
            dvr = "";
            tvr = "";
            sty = "";
            sid = "";
            ip = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Javascript
    {
        [global::Bond.Id(10)]
        public string libVer { get; set; }

        [global::Bond.Id(15)]
        public string osName { get; set; }

        [global::Bond.Id(20)]
        public string browser { get; set; }

        [global::Bond.Id(21)]
        public string browserVersion { get; set; }

        [global::Bond.Id(25)]
        public string platform { get; set; }

        [global::Bond.Id(30)]
        public string make { get; set; }

        [global::Bond.Id(35)]
        public string model { get; set; }

        [global::Bond.Id(40)]
        public string screenSize { get; set; }

        [global::Bond.Id(50)]
        public string mc1Id { get; set; }

        [global::Bond.Id(60)]
        public ulong mc1Lu { get; set; }

        [global::Bond.Id(70)]
        public bool isMc1New { get; set; }

        [global::Bond.Id(80)]
        public string ms0 { get; set; }

        [global::Bond.Id(90)]
        public string anid { get; set; }

        [global::Bond.Id(100)]
        public string a { get; set; }

        [global::Bond.Id(110)]
        public string msResearch { get; set; }

        [global::Bond.Id(120)]
        public string csrvc { get; set; }

        [global::Bond.Id(130)]
        public string rtCell { get; set; }

        [global::Bond.Id(140)]
        public string rtEndAction { get; set; }

        [global::Bond.Id(150)]
        public string rtPermId { get; set; }

        [global::Bond.Id(160)]
        public string r { get; set; }

        [global::Bond.Id(170)]
        public string wtFpc { get; set; }

        [global::Bond.Id(180)]
        public string omniId { get; set; }

        [global::Bond.Id(190)]
        public string gsfxSession { get; set; }

        [global::Bond.Id(200)]
        public string domain { get; set; }

        [global::Bond.Id(999)]
        public string dnt { get; set; }

        public Javascript()
            : this("CommonSchema.Javascript", "Javascript")
        {}

        protected Javascript(string fullName, string name)
        {
            libVer = "";
            osName = "";
            browser = "";
            browserVersion = "";
            platform = "";
            make = "";
            model = "";
            screenSize = "";
            mc1Id = "";
            ms0 = "";
            anid = "";
            a = "";
            msResearch = "";
            csrvc = "";
            rtCell = "";
            rtEndAction = "";
            rtPermId = "";
            r = "";
            wtFpc = "";
            omniId = "";
            gsfxSession = "";
            domain = "";
            dnt = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Protocol
    {
        [global::Bond.Id(1)]
        public int metadataCrc { get; set; }

        [global::Bond.Id(2)]
        public List<List<string>> ticketKeys { get; set; }

        [global::Bond.Id(3)]
        public string devMake { get; set; }

        [global::Bond.Id(4)]
        public string devModel { get; set; }

        public Protocol()
            : this("CommonSchema.Protocol", "Protocol")
        {}

        protected Protocol(string fullName, string name)
        {
            ticketKeys = new List<List<string>>();
            devMake = "";
            devModel = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Receipts
    {
        [global::Bond.Id(1)]
        public long originalTime { get; set; }

        [global::Bond.Id(2)]
        public long uploadTime { get; set; }

        public Receipts()
            : this("CommonSchema.Receipts", "Receipts")
        {}

        protected Receipts(string fullName, string name)
        {
            
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Net
    {
        [global::Bond.Id(1)]
        public string provider { get; set; }

        [global::Bond.Id(2)]
        public string cost { get; set; }

        [global::Bond.Id(3)]
        public string type { get; set; }

        public Net()
            : this("CommonSchema.Net", "Net")
        {}

        protected Net(string fullName, string name)
        {
            provider = "";
            cost = "";
            type = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Sdk
    {
        [global::Bond.Id(1)]
        public string libVer { get; set; }

        [global::Bond.Id(2)]
        public string epoch { get; set; }

        [global::Bond.Id(3)]
        public long seq { get; set; }

        [global::Bond.Id(4)]
        public string installId { get; set; }

        public Sdk()
            : this("CommonSchema.Sdk", "Sdk")
        {}

        protected Sdk(string fullName, string name)
        {
            libVer = "";
            epoch = "";
            installId = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Cloud
    {
        [global::Bond.Id(1)]
        public string fullEnvName { get; set; }

        [global::Bond.Id(2)]
        public string location { get; set; }

        [global::Bond.Id(3)]
        public string environment { get; set; }

        [global::Bond.Id(4)]
        public string deploymentUnit { get; set; }

        [global::Bond.Id(5)]
        public string name { get; set; }

        [global::Bond.Id(6)]
        public string roleInstance { get; set; }

        [global::Bond.Id(7)]
        public string role { get; set; }

        public Cloud()
            : this("CommonSchema.Cloud", "Cloud")
        {}

        protected Cloud(string fullName, string name)
        {
            fullEnvName = "";
            location = "";
            environment = "";
            deploymentUnit = "";
            this.name = "";
            roleInstance = "";
            role = "";
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum ValueKind
    {
        ValueInt64 = unchecked((int)0),
        ValueUInt64 = unchecked((int)1),
        ValueInt32 = unchecked((int)2),
        ValueUInt32 = unchecked((int)3),
        ValueDouble = unchecked((int)4),
        ValueString = unchecked((int)5),
        ValueBool = unchecked((int)6),
        ValueDateTime = unchecked((int)7),
        ValueGuid = unchecked((int)8),
        ValueArrayInt64 = unchecked((int)9),
        ValueArrayUInt64 = unchecked((int)10),
        ValueArrayInt32 = unchecked((int)11),
        ValueArrayUInt32 = unchecked((int)12),
        ValueArrayDouble = unchecked((int)13),
        ValueArrayString = unchecked((int)14),
        ValueArrayBool = unchecked((int)15),
        ValueArrayDateTime = unchecked((int)16),
        ValueArrayGuid = unchecked((int)17),
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum PIIKind
    {
        NotSet = unchecked((int)0),
        DistinguishedName = unchecked((int)1),
        GenericData = unchecked((int)2),
        IPV4Address = unchecked((int)3),
        IPv6Address = unchecked((int)4),
        MailSubject = unchecked((int)5),
        PhoneNumber = unchecked((int)6),
        QueryString = unchecked((int)7),
        SipAddress = unchecked((int)8),
        SmtpAddress = unchecked((int)9),
        Identity = unchecked((int)10),
        Uri = unchecked((int)11),
        Fqdn = unchecked((int)12),
        IPV4AddressLegacy = unchecked((int)13),
        IPv6ScrubLastHextets = unchecked((int)14),
        DropValue = unchecked((int)15),
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class PII
    {
        [global::Bond.Id(1)]
        public PIIKind Kind { get; set; }

        public PII()
            : this("CommonSchema.PII", "PII")
        {}

        protected PII(string fullName, string name)
        {
            Kind = PIIKind.NotSet;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum CustomerContentKind
    {
        NotSet = unchecked((int)0),
        GenericContent = unchecked((int)1),
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class CustomerContent
    {
        [global::Bond.Id(1)]
        public CustomerContentKind Kind { get; set; }

        public CustomerContent()
            : this("CommonSchema.CustomerContent", "CustomerContent")
        {}

        protected CustomerContent(string fullName, string name)
        {
            Kind = CustomerContentKind.NotSet;
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Attributes
    {
        [global::Bond.Id(1)]
        public List<PII> pii { get; set; }

        [global::Bond.Id(2)]
        public List<CustomerContent> customerContent { get; set; }

        public Attributes()
            : this("CommonSchema.Attributes", "Attributes")
        {}

        protected Attributes(string fullName, string name)
        {
            pii = new List<PII>();
            customerContent = new List<CustomerContent>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Value
    {
        [global::Bond.Id(1)]
        public ValueKind type { get; set; }

        [global::Bond.Id(2)]
        public List<Attributes> attributes { get; set; }

        [global::Bond.Id(3)]
        public string stringValue { get; set; }

        [global::Bond.Id(4)]
        public long longValue { get; set; }

        [global::Bond.Id(5)]
        public double doubleValue { get; set; }

        [global::Bond.Id(6)]
        public List<List<byte>> guidValue { get; set; }

        [global::Bond.Id(10)]
        public List<List<string>> stringArray { get; set; }

        [global::Bond.Id(11)]
        public List<List<long>> longArray { get; set; }

        [global::Bond.Id(12)]
        public List<List<double>> doubleArray { get; set; }

        [global::Bond.Id(13)]
        public List<List<List<byte>>> guidArray { get; set; }

        public Value()
            : this("CommonSchema.Value", "Value")
        {}

        protected Value(string fullName, string name)
        {
            type = ValueKind.ValueString;
            attributes = new List<Attributes>();
            stringValue = "";
            guidValue = new List<List<byte>>();
            stringArray = new List<List<string>>();
            longArray = new List<List<long>>();
            doubleArray = new List<List<double>>();
            guidArray = new List<List<List<byte>>>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class Data
    {
        [global::Bond.Id(1)]
        public Dictionary<string, Value> properties { get; set; }

        public Data()
            : this("CommonSchema.Data", "Data")
        {}

        protected Data(string fullName, string name)
        {
            properties = new Dictionary<string, Value>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class CsEvent
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string ver { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string name { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public long time { get; set; }

        [global::Bond.Id(4)]
        public double popSample { get; set; }

        [global::Bond.Id(5)]
        public string iKey { get; set; }

        [global::Bond.Id(6)]
        public long flags { get; set; }

        [global::Bond.Id(7)]
        public string cV { get; set; }

        [global::Bond.Id(20)]
        public List<Ingest> extIngest { get; set; }

        [global::Bond.Id(21)]
        public List<Protocol> extProtocol { get; set; }

        [global::Bond.Id(22)]
        public List<User> extUser { get; set; }

        [global::Bond.Id(23)]
        public List<Device> extDevice { get; set; }

        [global::Bond.Id(24)]
        public List<Os> extOs { get; set; }

        [global::Bond.Id(25)]
        public List<App> extApp { get; set; }

        [global::Bond.Id(26)]
        public List<Utc> extUtc { get; set; }

        [global::Bond.Id(27)]
        public List<Xbl> extXbl { get; set; }

        [global::Bond.Id(28)]
        public List<Javascript> extJavascript { get; set; }

        [global::Bond.Id(29)]
        public List<Receipts> extReceipts { get; set; }

        [global::Bond.Id(31)]
        public List<Net> extNet { get; set; }

        [global::Bond.Id(32)]
        public List<Sdk> extSdk { get; set; }

        [global::Bond.Id(33)]
        public List<Loc> extLoc { get; set; }

        [global::Bond.Id(34)]
        public List<Cloud> extCloud { get; set; }

        [global::Bond.Id(37)]
        public List<M365a> extM365a { get; set; }

        [global::Bond.Id(41)]
        public List<Data> ext { get; set; }

        [global::Bond.Id(51)]
        public Dictionary<string, string> tags { get; set; }

        [global::Bond.Id(60)]
        public string baseType { get; set; }

        [global::Bond.Id(61)]
        public List<Data> baseData { get; set; }

        [global::Bond.Id(70)]
        public List<Data> data { get; set; }

        public CsEvent()
            : this("CommonSchema.CsEvent", "CsEvent")
        {}

        protected CsEvent(string fullName, string name)
        {
            ver = "";
            this.name = "";
            popSample = 100.0;
            iKey = "";
            cV = "";
            extIngest = new List<Ingest>();
            extProtocol = new List<Protocol>();
            extUser = new List<User>();
            extDevice = new List<Device>();
            extOs = new List<Os>();
            extApp = new List<App>();
            extUtc = new List<Utc>();
            extXbl = new List<Xbl>();
            extJavascript = new List<Javascript>();
            extReceipts = new List<Receipts>();
            extNet = new List<Net>();
            extSdk = new List<Sdk>();
            extLoc = new List<Loc>();
            extCloud = new List<Cloud>();
            extM365a = new List<M365a>();
            ext = new List<Data>();
            tags = new Dictionary<string, string>();
            baseType = "";
            baseData = new List<Data>();
            data = new List<Data>();
        }
    }
} // CommonSchema
