#include <aria.h>

const char *TOKEN = "6d084bbf6a9644ef83f40a77c9e34580-c2d379e0-4408-4325-9b4d-2a7d78131e14-7322";

void test_c_api()
{
    // Ref. https://docs.microsoft.com/en-us/windows/privacy/basic-level-windows-diagnostic-events-and-fields for description of Common Schema fields
    aria_prop event[] = ARIA_EVENT
    (
        // Common Data Extensions.Envelope - reserved keywords that C API should not use.
        // Alternate solution is to declare a special macro for envelope 'root' namespace props,
        // such as $STR, $INT, etc.
        _STR("name",      "Event.Name.Pure.C"),  // Represents the uniquely qualified name for the event
        _STR("ver",       "3.0"),         // Represents the major and minor version of the extension
        _STR("time",      "1979-08-12"),  // Represents the event date time in Coordinated Universal Time(UTC) when the event was generated on the client.This should be in ISO 8601 format
        _INT("popSample", 100),           // Represents the effective sample rate for this event at the time it was generated by a client
        _STR("iKey",      TOKEN),         // Represents an ID for applications or other logical groupings of events.
        _INT("flags",     0xffffffff),    // Represents a collection of bits that describe how the event should be processed ...
        _STR("cV",        "12345"),       // Represents the Correlation Vector : A single field for tracking partial order of related telemetry events across component boundaries.

        // Customer Data fields go as part of userdata
           _STR("strKey", "value1"),
           _INT("intKey", 12345),
        PII_STR("piiKey", "secret", 1),   // TODO: copy-paste-translate the Pii Kind enum from C++ to C

        // Part "X" demo - populating CS extension props
        // Common Data Extensions.App
        PII_STR("ext.app.userId", "maxgolov@microsoft.com", 1),
           _STR("ext.app.ver",    "1.0.0")
    );

    aria_logevent(event);
    aria_flush();
    aria_upload();
    aria_teardown();
}