#include <stdio.h>
#include <stdlib.h>

#define _CRT_SECURE_LOG_S
#include "mat.h"

#define API_KEY "7c8b1796cbc44bd5a03803c01c2b9d61-b6e370dd-28d9-4a52-9556-762543cf7aa7-6991"

static const char* host_config =
    "{"
    "\"cacheFilePath\":\"MyOfflineStorage.db\","  // Custom storage path
    "\"config\":{\"host\": \"*\"},"
    "\"name\":\"C-API-Client-0\","                // Module ID
    "\"version\":\"1.0.0\","                      // Module semver
    "\"primaryToken\":\"" API_KEY
    "\","                                // Primary Token
    "\"maxTeardownUploadTimeInSec\":5,"  // Allow up to 5 seconds for upload
    "\"hostMode\":true,"                 // Explicitly declare as host
    "\"minimumTraceLevel\":0,"           // Debug printout level
    "\"sdkmode\":0"                      // 1DS direct-upload mode
    "}";

static const char* guest_config =
    "{"
    "\"cacheFilePath\":\"MyOfflineStorage.db\","  // Custom storage path
    "\"config\":{\"host\": \"*\"},"               // Attach as guest to any host
    "\"name\":\"C-API-Client-1\","                // Module ID
    "\"version\":\"1.0.0\","                      // Module semver
    "\"primaryToken\":\"" API_KEY
    "\","                                // Primary Token
    "\"maxTeardownUploadTimeInSec\":5,"  // Allow up to 5 seconds for upload
    "\"hostMode\":false,"                // Explicitly declare yourself as guest
    "\"minimumTraceLevel\":0,"           // Debug printout level
    "\"sdkmode\":0"                      // 1DS direct-upload mode
    "}";


evt_handle_t host_handle = 0;

evt_handle_t guest_handle = 0;

/**
 * Initialize as Host - main owner of LogManager instance.
 */
void test_c_api_host()
{
    evt_prop event[] = TELEMETRY_EVENT(
        // Common Data Extensions.Envelope - reserved keywords that C API should not use.
        // Alternate solution is to declare a special macro for envelope 'root' namespace props,
        // such as $STR, $INT, etc.
        _STR("name", "TestApp.Event.Host"),        // Represents the uniquely qualified name for the event
        _STR("ver", "3.0"),                        // Represents the major and minor version of the extension
                                                   //   _STR("time",      "1979-08-12"),  // Represents the event date time in Coordinated Universal Time(UTC) when the event was generated on the client.This should be in ISO 8601 format
        _INT("popSample", 100),                    // Represents the effective sample rate for this event at the time it was generated by a client
        _STR("iKey", API_KEY),                     // Represents an ID for applications or other logical groupings of events.
        _INT("flags", 0xffffffff),                 // Represents a collection of bits that describe how the event should be processed ...
        _STR("cV", "12345"),                       // Represents the Correlation Vector : A single field for tracking partial order of related telemetry events across component boundaries.
        // Customer Data fields go as part of userdata
        _STR("strKey", "value1"),
        _INT("intKey", 12345),
        PII_STR("piiKey", "secret", 1),
        // Part "X" demo - populating CS extension props
        // Common Data Extensions.App
        PII_STR("ext.app.userId", "jackfrost@microsoft.com", 1),
        _STR("ext.app.ver", "1.0.0"));

#ifdef _WIN32
    // It is possible to delay-load the loading of default ClientTelemetry.dll ,
    // then load an alternate implementation with a matching set of exported syms.
    // That way the calls are essentially redirected to user-supplied telemetry
    printf("Loading ClientTelemetry implementation library...\n");
    evt_load((evt_handle_t)LoadLibrary(L"ClientTelemetry.dll"));
#endif

    printf("Testing C API (host)...\n");
    host_handle = evt_open(host_config);

    printf("evt_log(host_handle)\n");
    evt_log(host_handle, event);

    printf("evt_flush(host_handle)\n");
    evt_flush(host_handle);

    printf("evt_upload(host_handle)\n");
    evt_upload(host_handle);
}

/**
 * Initialize as Guest - SDK in the main app, anchor to existing LogManager instance.
 */
void test_c_api_guest()
{
#ifdef _WIN32
    // Check if we can load the same library again.
    printf("Loading ClientTelemetry implementation library (again)...\n");
    evt_load((evt_handle_t)LoadLibrary(L"ClientTelemetry.dll"));
#endif

    printf("Testing C API (guest)...\n");
    guest_handle = evt_open(guest_config);

    // Ref. https://docs.microsoft.com/en-us/windows/privacy/basic-level-windows-diagnostic-events-and-fields for description of Common Schema fields
    evt_prop event[] = TELEMETRY_EVENT(
        // Common Data Extensions.Envelope - reserved keywords that C API should not use.
        // Alternate solution is to declare a special macro for envelope 'root' namespace props,
        // such as $STR, $INT, etc.
        _STR("name", "TestApp.Event.Guest"),  // Represents the uniquely qualified name for the event
        _STR("ver", "3.0"),                   // Represents the major and minor version of the extension
        _STR("time", "1979-08-12"),           // Represents the event date time in Coordinated Universal Time(UTC) when the event was generated on the client.This should be in ISO 8601 format
        _INT("popSample", 100),               // Represents the effective sample rate for this event at the time it was generated by a client
        _STR("iKey", API_KEY),                // Represents an ID for applications or other logical groupings of events.
        _INT("flags", 0xffffffff),            // Represents a collection of bits that describe how the event should be processed ...
        _STR("cV", "12345"),                  // Represents the Correlation Vector : A single field for tracking partial order of related telemetry events across component boundaries.
                                              // Customer Data fields go as part of userdata
        _STR("strKey", "value1"),
        _INT("intKey", 12345),
        PII_STR("piiKey", "secret", 1),
        // Part "X" demo - populating CS extension props
        // Common Data Extensions.App
        PII_STR("ext.app.userId", "jackfrost@microsoft.com", 1),
        _STR("ext.app.ver", "1.0.0"));

    printf("evt_log(guest_handle)\n");
    evt_log(guest_handle, event);

    printf("evt_flush(guest_handle)\n");
    evt_flush(guest_handle);

    printf("evt_upload(guest_handle)\n");
    evt_upload(guest_handle);
}

int main(int argc, char* argv[])
{
    printf("Hello, C API... ");

    // Send events as Host
    test_c_api_host();
    // Send events as Guest
    test_c_api_guest();

    // Close Host handle
    printf("evt_close(host_handle)\n");
    evt_close(host_handle);

    // Close Guest handle
    printf("evt_close(guest_handle)\n");
    evt_close(guest_handle);

    printf("[ DONE ]\n");
    return 0;
}
