#include "mat.h"

#include <stdio.h>
#include <stdlib.h>

void test_c_api(const char * token)
{

#if 0 /* No JSON parser in smallest SKU */
    static const char* config_template =
        "{"
        "\"cacheFilePath\":\"MyOfflineStorage.db\","  // Custom storage path
        "\"config\":{\"host\": \"*\"},"               // Attach as guest to any host
        "\"name\":\"C-API-Client-0\","                // Module ID
        "\"version\":\"1.0.0\","                      // Module semver
        "\"primaryToken\":\"%s\","           // Primary Token
        "\"maxTeardownUploadTimeInSec\":5,"           // Allow up to 5 seconds for upload
        "\"hostMode\":false,"                         // Explicitly declare yourself as guest
        "\"minimumTraceLevel\":0,"                    // Debug printout level
        "\"sdkmode\":0"                               // SDK direct-upload mode
        "}";
    static char config[1024] = { 0 };
    snprintf(config, sizeof(config), config_template, token);
#endif

    printf("Testing C API...\t");

#if 1   // Initialize using TOKEN
    evt_handle_t handle = evt_open(token);
#else   // Initialize using ILogConfiguration in JSON format
    evt_handle_t handle = evt_open((const char *)config);
#endif

    // Ref. https://docs.microsoft.com/en-us/windows/privacy/basic-level-windows-diagnostic-events-and-fields for description of Common Schema fields
    evt_prop event[] = TELEMETRY_EVENT
    (
        // Common Data Extensions.Envelope - reserved keywords that C API should not use.
        // Alternate solution is to declare a special macro for envelope 'root' namespace props,
        // such as $STR, $INT, etc.
        _STR("name", "Event.Name.Pure.C"), // Represents the uniquely qualified name for the event
        _STR("ver", "3.0"),                // Represents the major and minor version of the extension
        _STR("time", "1979-08-12"),        // Represents the event date time in Coordinated Universal Time(UTC) when the event was generated on the client.This should be in ISO 8601 format
        _INT("popSample", 100),            // Represents the effective sample rate for this event at the time it was generated by a client
        _STR("iKey", token),               // Represents an ID for applications or other logical groupings of events.
        _INT("flags", 0xffffffff),         // Represents a collection of bits that describe how the event should be processed ...
        _STR("cV", "12345"),               // Represents the Correlation Vector : A single field for tracking partial order of related telemetry events across component boundaries.
        // Customer Data fields go as part of userdata
        _STR("strKey", "value1"),
        _INT("intKey", 12345),
        PII_STR("piiKey", "secret", 1),
        // Part "X" demo - populating CS extension props
        // Common Data Extensions.App
        PII_STR("ext.app.userId", "jackfrost@microsoft.com", 1),
        _STR("ext.app.ver", "1.0.0")
    );

    evt_log(handle, event);
    evt_flush(handle);
    evt_upload(handle);
    evt_close(handle);

    printf("[ DONE ]\n");
}
