cmake_minimum_required(VERSION 3.19)

get_filename_component(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(REGISTRY_MODE)
  set(ENV{MATSDK_VCPKG_SOURCE_DIR} "${REPO_ROOT}/does-not-exist")
else()
  set(ENV{MATSDK_VCPKG_SOURCE_DIR} "${REPO_ROOT}")
endif()

function(vcpkg_from_github)
  cmake_parse_arguments(FETCH "" "OUT_SOURCE_PATH;REPO;REF;SHA512;HEAD_REF" "" ${ARGN})
  string(LENGTH "${FETCH_SHA512}" hash_length)
  if(NOT FETCH_REPO STREQUAL "microsoft/cpp_client_telemetry"
      OR NOT FETCH_REF MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
      OR NOT FETCH_SHA512 MATCHES "^[0-9a-f]+$" OR NOT hash_length EQUAL 128)
    message(FATAL_ERROR "Registry source must be a hash-verified release archive.")
  endif()
  set("${FETCH_OUT_SOURCE_PATH}" "${REPO_ROOT}" PARENT_SCOPE)
  set(FETCHED ON PARENT_SCOPE)
endfunction()

function(vcpkg_check_features)
  cmake_parse_arguments(CHECK "" "OUT_FEATURE_OPTIONS" "FEATURES" ${ARGN})
  set(options)
  while(CHECK_FEATURES)
    list(POP_FRONT CHECK_FEATURES feature option)
    set(value OFF)
    if(feature IN_LIST FEATURES)
      set(value ON)
    endif()
    list(APPEND options "-D${option}=${value}")
  endwhile()
  set("${CHECK_OUT_FEATURE_OPTIONS}" "${options}" PARENT_SCOPE)
endfunction()

function(vcpkg_cmake_configure)
  cmake_parse_arguments(CONFIG "" "SOURCE_PATH" "OPTIONS" ${ARGN})
  foreach(option IN LISTS EXPECTED_OPTIONS)
    if(NOT "${option}" IN_LIST CONFIG_OPTIONS)
      message(FATAL_ERROR "Missing ${option}: ${CONFIG_OPTIONS}")
    endif()
  endforeach()
  set(LEGACY_OPTIONS)
  foreach(option IN LISTS CONFIG_OPTIONS)
    if(REGISTRY_MODE AND option MATCHES "^-DMATSDK_DISABLE_(EXCEPTIONS|LOGGING)=")
      message(FATAL_ERROR "Registry features must not override compile policy: ${option}")
    endif()
    if(option MATCHES "^-D(MATSDK_USE_VCPKG_DEPS|MATSDK_MINIMAL_SQLITE)=")
      message(FATAL_ERROR "Obsolete dependency option was forwarded: ${option}")
    endif()
    if(option MATCHES "^-DBUILD_(HEADERS|LIBRARY|TEST_TOOL|UNIT_TESTS|FUNC_TESTS|JNI_WRAPPER|OBJC_WRAPPER|SWIFT_WRAPPER|PACKAGE|APPLE_HTTP)=")
      list(APPEND LEGACY_OPTIONS "${option}")
    endif()
  endforeach()
  if(NOT "${LEGACY_OPTIONS}" STREQUAL "${EXPECTED_LEGACY_OPTIONS}")
    message(FATAL_ERROR "Incorrect legacy build options: ${LEGACY_OPTIONS}")
  endif()
  set(CONFIGURED ON PARENT_SCOPE)
endfunction()

function(vcpkg_cmake_install)
endfunction()
function(vcpkg_cmake_config_fixup)
endfunction()
function(vcpkg_install_copyright)
endfunction()

function(check_feature_mapping platform linkage)
  set(FEATURES ${ARGN})
  set(VERSION 3.10.999.1)
  set(CURRENT_PORT_DIR "${REPO_ROOT}/tools/ports/cpp-client-telemetry")
  if(REGISTRY_MODE)
    set(CURRENT_PORT_DIR "${REPO_ROOT}/tools/registry-ports/cpp-client-telemetry")
  endif()
  set(CURRENT_PACKAGES_DIR "${REPO_ROOT}/out/native-feature-tests")
  set(VCPKG_LIBRARY_LINKAGE "${linkage}")
  foreach(target LINUX WINDOWS OSX IOS ANDROID)
    set(VCPKG_TARGET_IS_${target} OFF)
  endforeach()
  set(VCPKG_TARGET_IS_${platform} ON)
  set(EXPECTED_OPTIONS
    -DMATSDK_BUILD_HEADERS=ON -DMATSDK_BUILD_LIBRARY=ON
    -DMATSDK_BUILD_TEST_TOOL=OFF -DMATSDK_BUILD_UNIT_TESTS=OFF
    -DMATSDK_BUILD_FUNC_TESTS=OFF -DMATSDK_BUILD_PACKAGE=OFF
    -DMATSDK_BUILD_JNI_WRAPPER=OFF -DMATSDK_BUILD_OBJC_WRAPPER=OFF
    -DMATSDK_BUILD_SWIFT_WRAPPER=OFF)
  foreach(pair IN ITEMS
      "no-exceptions|MATSDK_DISABLE_EXCEPTIONS"
      "no-logging|MATSDK_DISABLE_LOGGING"
      "android-capi-http-client|MATSDK_ENABLE_CAPI_HTTP_CLIENT"
      "device-id|MATSDK_ENABLE_DEVICE_ID"
      "wininet|MATSDK_USE_WININET")
    string(REPLACE "|" ";" pair "${pair}")
    list(GET pair 0 feature)
    list(GET pair 1 option)
    if(REGISTRY_MODE AND feature MATCHES "^(no-exceptions|no-logging|wininet)$")
      continue()
    endif()
    set(enabled OFF)
    if(feature IN_LIST FEATURES)
      set(enabled ON)
    endif()
    list(APPEND EXPECTED_OPTIONS "-D${option}=${enabled}")
  endforeach()
  set(shared OFF)
  if(linkage STREQUAL "dynamic")
    set(shared ON)
  endif()
  list(APPEND EXPECTED_OPTIONS "-DBUILD_SHARED_LIBS=${shared}")
  set(sqlite SYSTEM)
  if(NOT REGISTRY_MODE AND "minimal-sqlite" IN_LIST FEATURES)
    set(sqlite MINIMAL)
  endif()
  list(APPEND EXPECTED_OPTIONS "-DMATSDK_SQLITE_PROVIDER=${sqlite}")
  if(REGISTRY_MODE)
    list(APPEND EXPECTED_OPTIONS
      -DMATSDK_ZLIB_PROVIDER=SYSTEM -DMATSDK_CURL_PROVIDER=SYSTEM
      -DMATSDK_USE_WININET=OFF
      -DBUILD_VERSION=3.10.999.1)
  endif()
  set(apple_http OFF)
  if(platform STREQUAL "OSX" OR platform STREQUAL "IOS")
    set(apple_http ON)
  endif()
  list(APPEND EXPECTED_OPTIONS "-DMATSDK_BUILD_APPLE_HTTP=${apple_http}")
  set(android_http AUTO)
  if(REGISTRY_MODE AND platform STREQUAL "ANDROID")
    set(android_http JAVA)
  elseif(platform STREQUAL "ANDROID"
      AND ("android-curl-openssl" IN_LIST FEATURES OR "android-curl-mbedtls" IN_LIST FEATURES))
    set(android_http CURL)
  endif()
  list(APPEND EXPECTED_OPTIONS "-DMATSDK_ANDROID_HTTP_CLIENT=${android_http}")
  set(CONFIGURED OFF)
  set(FETCHED OFF)
  include("${CURRENT_PORT_DIR}/portfile.cmake")
  if(NOT CONFIGURED)
    message(FATAL_ERROR "The feature mapping did not configure the SDK.")
  endif()
  if(REGISTRY_MODE AND NOT FETCHED)
    message(FATAL_ERROR "Registry port bypassed the pinned archive.")
  endif()
endfunction()

if(REGISTRY_MODE)
  foreach(platform LINUX WINDOWS OSX IOS ANDROID)
    foreach(linkage static dynamic)
      foreach(features IN ITEMS "" device-id)
        check_feature_mapping("${platform}" "${linkage}" ${features})
      endforeach()
      if(platform STREQUAL "ANDROID")
        foreach(features IN ITEMS android-capi-http-client
            "device-id;android-capi-http-client")
          check_feature_mapping("${platform}" "${linkage}"
            ${features})
        endforeach()
      endif()
    endforeach()
  endforeach()
  message(STATUS "Registry additive features, core graphs, and fixed platform transports passed")
  return()
endif()

if(DEFINED UNSUPPORTED_FEATURE)
  set(ENV{MATSDK_VCPKG_SOURCE_DIR} "${OLD_SOURCE}")
  if(UNSUPPORTED_FEATURE STREQUAL "minimal-sqlite")
    check_feature_mapping(ANDROID static device-id minimal-sqlite)
  else()
    check_feature_mapping(ANDROID static device-id system-sqlite "${UNSUPPORTED_FEATURE}")
  endif()
  return()
endif()

file(READ "${REPO_ROOT}/tools/ports/cpp-client-telemetry/vcpkg.json" MANIFEST)
foreach(feature no-exceptions no-logging android-capi-http-client)
  string(JSON DESCRIPTION GET "${MANIFEST}" features "${feature}" description)
endforeach()
string(JSON CAPI_PLATFORMS GET "${MANIFEST}" features android-capi-http-client supports)
if(NOT CAPI_PLATFORMS STREQUAL "android")
  message(FATAL_ERROR "Custom Android C API HTTP callbacks must be Android-only.")
endif()
string(JSON DEFAULT_COUNT LENGTH "${MANIFEST}" default-features)
math(EXPR DEFAULT_LAST "${DEFAULT_COUNT} - 1")
set(DEFAULT_FEATURES)
foreach(index RANGE ${DEFAULT_LAST})
  string(JSON FEATURE GET "${MANIFEST}" default-features ${index})
  if(FEATURE MATCHES "^(no-exceptions|no-logging|android-capi-http-client)$")
    message(FATAL_ERROR "${FEATURE} must remain opt-in.")
  endif()
  list(APPEND DEFAULT_FEATURES "${FEATURE}")
endforeach()
check_feature_mapping(LINUX static ${DEFAULT_FEATURES})

foreach(platform LINUX WINDOWS OSX IOS ANDROID)
  foreach(linkage static dynamic)
    foreach(options IN ITEMS "" "no-exceptions" "no-logging" "no-exceptions;no-logging")
      check_feature_mapping("${platform}" "${linkage}"
        device-id curl-openssl system-sqlite ${options})
      check_feature_mapping("${platform}" "${linkage}"
        curl-mbedtls minimal-sqlite ${options})
    endforeach()
  endforeach()
endforeach()
check_feature_mapping(WINDOWS static wininet minimal-sqlite no-exceptions no-logging)
foreach(transport "" android-curl-openssl android-curl-mbedtls)
  check_feature_mapping(ANDROID static
    minimal-sqlite android-capi-http-client no-exceptions no-logging ${transport})
endforeach()

set(OLD_SOURCE "${REPO_ROOT}/out/native-feature-tests/older-source")
file(MAKE_DIRECTORY "${OLD_SOURCE}")
file(WRITE "${OLD_SOURCE}/CMakeLists.txt"
  "# MATSDK_ANDROID_HTTP_CLIENT MATSDK_USE_WININET MATSDK_ENABLE_DEVICE_ID\n")
foreach(feature no-exceptions no-logging android-capi-http-client minimal-sqlite)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" "-DUNSUPPORTED_FEATURE=${feature}"
      "-DOLD_SOURCE=${OLD_SOURCE}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_VARIABLE ERROR)
  if(RESULT EQUAL 0 OR NOT ERROR MATCHES "The ${feature} feature requires")
    message(FATAL_ERROR "Unsupported ${feature} must fail explicitly: ${ERROR}")
  endif()
endforeach()

file(APPEND "${OLD_SOURCE}/CMakeLists.txt"
  "# MATSDK_USE_VCPKG_DEPS MATSDK_MINIMAL_SQLITE MATSDK_SQLITE_PROVIDER\n")
set(ENV{MATSDK_VCPKG_SOURCE_DIR} "${OLD_SOURCE}")
set(EXPECTED_LEGACY_OPTIONS
  -DBUILD_HEADERS=ON -DBUILD_LIBRARY=ON -DBUILD_TEST_TOOL=OFF
  -DBUILD_UNIT_TESTS=OFF -DBUILD_FUNC_TESTS=OFF -DBUILD_JNI_WRAPPER=OFF
  -DBUILD_OBJC_WRAPPER=OFF -DBUILD_SWIFT_WRAPPER=OFF -DBUILD_PACKAGE=OFF
  -DBUILD_APPLE_HTTP=OFF)
check_feature_mapping(LINUX static device-id curl-openssl minimal-sqlite)
list(REMOVE_ITEM EXPECTED_LEGACY_OPTIONS -DBUILD_APPLE_HTTP=OFF)
list(APPEND EXPECTED_LEGACY_OPTIONS -DBUILD_APPLE_HTTP=ON)
check_feature_mapping(IOS static device-id minimal-sqlite)

file(APPEND "${OLD_SOURCE}/CMakeLists.txt"
  "option(MATSDK_BUILD_HEADERS \"Build API headers\" ON)\n")
list(REMOVE_ITEM EXPECTED_LEGACY_OPTIONS -DBUILD_HEADERS=ON -DBUILD_APPLE_HTTP=ON)
list(APPEND EXPECTED_LEGACY_OPTIONS -DBUILD_APPLE_HTTP=OFF)
check_feature_mapping(ANDROID static device-id system-sqlite)
file(REMOVE "${OLD_SOURCE}/CMakeLists.txt")
message(STATUS "Native vcpkg feature mappings passed")
