cmake_minimum_required(VERSION 3.19)

get_filename_component(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(NOT DEFINED OUTPUT_DIR)
  set(OUTPUT_DIR "${REPO_ROOT}/out/package-dependency-tests")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT_DIR}/MSTelemetryTargets.cmake" "")
file(WRITE "${OUTPUT_DIR}/MatsdkDependencyTargets.cmake" [=[
function(matsdk_add_package_system_dependency target canonical provider package)
  cmake_parse_arguments(DEPENDENCY "APPLE_SYSTEM" "APPLE_LIBRARY;LEGACY_TARGET" "" ${ARGN})
  if(NOT provider STREQUAL "SYSTEM")
    message(FATAL_ERROR "Unexpected provider for ${package}: ${provider}")
  endif()
  if((DEPENDENCY_APPLE_SYSTEM AND NOT EXPECTED_APPLE_SYSTEM)
      OR (NOT DEPENDENCY_APPLE_SYSTEM AND EXPECTED_APPLE_SYSTEM))
    message(FATAL_ERROR "Incorrect Apple dependency selection for ${package}")
  endif()
  if(DEPENDENCY_APPLE_SYSTEM)
    if(package STREQUAL "SQLite3")
      set(expected_library sqlite3)
    elseif(package STREQUAL "ZLIB")
      set(expected_library z)
    else()
      message(FATAL_ERROR "Unexpected Apple dependency: ${package}")
    endif()
    if(NOT DEPENDENCY_APPLE_LIBRARY STREQUAL expected_library)
      message(FATAL_ERROR "Incorrect Apple library for ${package}")
    endif()
  endif()
  set_property(GLOBAL APPEND PROPERTY RESOLVED_DEPENDENCIES "${package}")
endfunction()
]=])

set(PACKAGE_INIT "macro(check_required_components name)\nendmacro()")
set(MATSDK_SQLITE_PROVIDER_RESOLVED SYSTEM)
set(MATSDK_ZLIB_PROVIDER_RESOLVED SYSTEM)
set(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED NONE)
set(MATSDK_NEEDS_CURL OFF)
set(MATSDK_CURL_FETCHED OFF)
set(CMAKE_SYSTEM_NAME Darwin)

foreach(MATSDK_BUILD_PLATFORM_APPLE ON OFF)
  foreach(MATSDK_USING_VCPKG ON OFF)
    foreach(MATSDK_CONFIG_STATIC_PACKAGE ON OFF)
      set(EXPECTED_APPLE_SYSTEM OFF)
      if(MATSDK_BUILD_PLATFORM_APPLE AND NOT MATSDK_USING_VCPKG)
        set(EXPECTED_APPLE_SYSTEM ON)
      endif()
      set_property(GLOBAL PROPERTY RESOLVED_DEPENDENCIES "")
      configure_file("${REPO_ROOT}/cmake/MSTelemetryConfig.cmake.in"
        "${OUTPUT_DIR}/MSTelemetryConfig.cmake" @ONLY)
      include("${OUTPUT_DIR}/MSTelemetryConfig.cmake")
      get_property(dependencies GLOBAL PROPERTY RESOLVED_DEPENDENCIES)
      if(MATSDK_CONFIG_STATIC_PACKAGE)
        if(NOT dependencies STREQUAL "SQLite3;ZLIB")
          message(FATAL_ERROR "Missing static package dependencies: ${dependencies}")
        endif()
      elseif(dependencies)
        message(FATAL_ERROR "Shared packages must not rediscover private dependencies")
      endif()
    endforeach()
  endforeach()
endforeach()

message(STATUS "Package dependency selection passed for all eight configurations")
