#pragma once

namespace Microsoft { namespace Applications { namespace Telemetry {


    /// <summary>
    /// Levels of ARIASDK_LOG_DETAIL events that represents printf style logging generated by an application
    /// </summary>
    enum ARIASDK_LOG_DETAILLevel
    {
        ARIASDK_LOG_DETAILLevel_None             = 0,
        ARIASDK_LOG_DETAILLevel_Error            = 1,
        ARIASDK_LOG_DETAILLevel_Warning          = 2,
        ARIASDK_LOG_DETAILLevel_Information      = 3,
        ARIASDK_LOG_DETAILLevel_Verbose          = 4
    };

}}}