#define EVTSDK_VERSION_PREFIX "EVT"
#define HAVE_MAT_JSONHPP
#define HAVE_MAT_ZLIB
/* #define HAVE_MAT_LOGGING    */
/* #define HAVE_MAT_STORAGE    */
/* #define HAVE_MAT_NETDETECT  */
/* #define HAVE_MAT_SHORT_NS   */
#define HAVE_MAT_DEFAULT_HTTP_CLIENT
