android {
    compileSdk 34

    ndkVersion           =  System.getenv("ANDROID_NDK_VERSION") ?: "27.0.12077973"

    defaultConfig {
      minSdk 23
      targetSdk 34
      externalNativeBuild {
        cmake {
          arguments "-DMATSDK_ENABLE_DEVICE_ID=" +
              (project.findProperty("MATSDK_ENABLE_DEVICE_ID") ?:
                  System.getenv("MATSDK_ENABLE_DEVICE_ID") ?: "ON")
        }
      }
    }
}

if (file('tools.gradle.user').exists()) {
  apply from: 'tools.gradle.user'
}
