[package]
name = "msft-client-telemetry"
version = "0.1.0"
edition = "2021"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]

[build-dependencies]
bindgen = "0.65.1"