//
// Copyright (c) 2015-2020 Microsoft Corporation and Contributors.
// SPDX-License-Identifier: Apache-2.0
//
package com.microsoft.applications.events;

/**
 * The TraceLevel enumeration contains a set of values that specify various levels of trace events&mdash;that represent
 * printf-style logging details generated by an application.
 */
public enum TraceLevel {
    /**
     * No trace event level.
     */
    None(0),

    /**
     * Error level.
     */
    Error(1),

    /**
     * Warning level.
     */
    Warning(2),

    /**
     * Information level.
     */
    Information(3),

    /**
     * Verbose level.
     */
    Verbose(4);

    private final int m_value;

    TraceLevel(int value) {
        m_value = value;
    }

    int getValue() {
        return m_value;
    }
}

