= Building for Android
Martin Harriman

== Building: Where to Start
The ``lib/android_build`` directory contains the gradle configuration needed to build both the sdk library and an empty test application. There are at least three ways to use this to build for Android:

Android Studio:: Open ```lib/android_build``` (or import its gradle configuration) in Android Studio, then build as usual.
Gradle Wrapper:: In ```lib/android_build```, run ``gradlew`` (Linux) or ``gradlew.bat`` (Windows) with the ``assemble`` task:
 ** ``./gradlew assemble``
 ** ``.\gradlew.bat assemble``
Docker Container:: This combines all of the tools required to build the SDK, which is convenient if your environment does not have the required Android SDK, NDK, CMake and ninja tools. See <<How to Use the Docker Container>> below for details.

== Build Artifacts: Where's My Stuff?
After building, via Android Studio, gradle, or Docker, the results appear in ten files in the `ariasdk/build/` subdirectory. If you build with Android Studio or gradle, this appears as a subdirectory of `lib/android_build`. For Docker (see <<<Run in a Docker Container>>>), you control where the artifacts will appear.

* ``outputs/aar/ariasdk-release.aar`` Release-build Android library (for the Java component of the SDK)
* ``outputs/aar/ariasdk-debug.aar`` Debug-build Android library
* ``intermediates/merged_native_libs/release/out/lib/`` Release-mode .so (native) libraries for each ABI
** ``x86/libsdk-lib.so``
** ``armeabi-v7a/libsdk-lib.so``
** ``x86_64/libsdk-lib.so``
** ``arm64-v8a/libsdk-lib.so``
* ``intermediates/merged_native_libs/debug/out/lib/`` Debug-build .so libraries for the same 4 ABIs.

== How to Use the Docker Container ==
=== Install Docker
The first prerequisite is to install Docker for your environment.

* *Windows* https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe
* *MacOS* https://download.docker.com/mac/stable/Docker.dmg
* *Linux* https://hub.docker.com/search/?type=edition&offering=community 

=== Clone or Checkout with Linefeeds
For Windows Docker, you will need a Linux LF-end-of-line copy of the SDK; on Linux or MacOS, the default git clone command will give you the appropriate line-feed end of line flavor automatically.

==== Windows

----
 git clone --config core.autocrlf=false git@github.com:microsoft/cpp_client_telemetry.git
----

==== Mac and Linux
----
git clone git@github.com:microsoft/cpp_client_telemetry.git
----

=== Build the Docker image
For the default Linux installation of Docker, you must run docker commands with sudo. For Windows, you do not need an elevated (run-as-administrator) shell. Run this command from the root (cpp_client_telemetry) of your git working directory:

----
docker build -f docker/android/Dockerfile . -t ariabuild
----

This may take some time to complete the first time you do this. You must re-do this before building any time the source code changes, since it copies the source tree into the image at build time.

==== Run in a Docker Container
Create a directory to hold the build artifacts. For purposes of illustration, suppose your artifact directory is E:\SomeDirectory. Then the command to build the SDK and load a tar file of the results into E:\SomeDirectory is:

----
docker run --mount type=bind,src=/e/SomeDirectory,dst=/artifacts ariabuild:latest
----

==== Artifacts
If the build succeeds, the container will write an artifacts.tar file into your output directory:

----
tar xvf .\artifacts.tar
x ariasdk/build/outputs/aar/
x ariasdk/build/outputs/aar/ariasdk-release.aar
x ariasdk/build/outputs/aar/ariasdk-debug.aar
x ariasdk/build/intermediates/merged_native_libs/
x ariasdk/build/intermediates/merged_native_libs/release/
x ariasdk/build/intermediates/merged_native_libs/release/out/
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/x86/
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/x86/libsdk-lib.so
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/libsdk-lib.so
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/x86_64/
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/x86_64/libsdk-lib.so
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/
x ariasdk/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libsdk-lib.so
x ariasdk/build/intermediates/merged_native_libs/debug/
x ariasdk/build/intermediates/merged_native_libs/debug/out/
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/x86/
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/x86/libsdk-lib.so
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/armeabi-v7a/
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/armeabi-v7a/libsdk-lib.so
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/x86_64/
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/x86_64/libsdk-lib.so
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/arm64-v8a/
x ariasdk/build/intermediates/merged_native_libs/debug/out/lib/arm64-v8a/libsdk-lib.so
----