function(matsdk_bool_option canonical legacy description default_value)
  set(initial_value "${default_value}")
  set(canonical_predefined OFF)
  if(DEFINED ${canonical})
    set(canonical_predefined ON)
  endif()
  set(legacy_defined OFF)
  if(NOT "${legacy}" STREQUAL "")
    if(DEFINED ${legacy})
      set(legacy_defined ON)
      if(NOT canonical_predefined)
        set(initial_value "${${legacy}}")
      endif()
    endif()
  endif()
  option(${canonical} "${description}" "${initial_value}")
  if(canonical_predefined AND legacy_defined
     AND NOT "${${legacy}}" STREQUAL "${${canonical}}")
    message(DEPRECATION
      "${legacy} is deprecated and conflicts with ${canonical}; "
      "${canonical}=${${canonical}} takes precedence.")
  endif()
endfunction()

if(DEFINED PROJECT_IS_TOP_LEVEL)
  set(MATSDK_PROJECT_IS_TOP_LEVEL "${PROJECT_IS_TOP_LEVEL}")
elseif(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  set(MATSDK_PROJECT_IS_TOP_LEVEL ON)
else()
  set(MATSDK_PROJECT_IS_TOP_LEVEL OFF)
endif()

matsdk_bool_option(MATSDK_BUILD_HEADERS BUILD_HEADERS
  "Build API headers" ON)
matsdk_bool_option(MATSDK_BUILD_LIBRARY BUILD_LIBRARY
  "Build the SDK library" ON)
matsdk_bool_option(MATSDK_BUILD_TEST_TOOL BUILD_TEST_TOOL
  "Build the console test tool" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
matsdk_bool_option(MATSDK_BUILD_UNIT_TESTS BUILD_UNIT_TESTS
  "Build unit tests" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
matsdk_bool_option(MATSDK_BUILD_FUNC_TESTS BUILD_FUNC_TESTS
  "Build functional tests" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
matsdk_bool_option(MATSDK_BUILD_JNI_WRAPPER BUILD_JNI_WRAPPER
  "Build the JNI wrapper" OFF)
matsdk_bool_option(MATSDK_ANDROID_USE_ROOM USE_ROOM
  "Use Android Room for offline storage" OFF)
matsdk_bool_option(MATSDK_ENABLE_CAPI_HTTP_CLIENT ENABLE_CAPI_HTTP_CLIENT
  "Enable the C API HTTP client on Android" OFF)
matsdk_bool_option(MATSDK_BUILD_OBJC_WRAPPER BUILD_OBJC_WRAPPER
  "Build the Objective-C wrapper" ON)
matsdk_bool_option(MATSDK_BUILD_SWIFT_WRAPPER BUILD_SWIFT_WRAPPER
  "Build Swift wrappers" ON)
matsdk_bool_option(MATSDK_BUILD_PACKAGE BUILD_PACKAGE
  "Build an SDK package" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
matsdk_bool_option(MATSDK_BUILD_PRIVACYGUARD BUILD_PRIVACYGUARD
  "Build Privacy Guard" ON)
matsdk_bool_option(MATSDK_BUILD_CDS BUILD_CDS
  "Build Common Diagnostic Stack" ON)
matsdk_bool_option(MATSDK_BUILD_LIVEEVENTINSPECTOR BUILD_LIVEEVENTINSPECTOR
  "Build Live Event Inspector" ON)
matsdk_bool_option(MATSDK_BUILD_SIGNALS BUILD_SIGNALS
  "Build Signals" ON)
matsdk_bool_option(MATSDK_BUILD_SANITIZER BUILD_SANITIZER
  "Build Sanitizer" ON)
matsdk_bool_option(MATSDK_BUILD_AZMON BUILD_AZMON
  "Build Azure Monitor / Application Insights support" ON)
matsdk_bool_option(MATSDK_BUILD_APPLE_HTTP BUILD_APPLE_HTTP
  "Build the Apple-native HTTP client" "${APPLE}")

set(MATSDK_ANDROID_HTTP_CLIENT "AUTO" CACHE STRING
  "Android HTTP client: AUTO, JAVA, or CURL")
set_property(CACHE MATSDK_ANDROID_HTTP_CLIENT PROPERTY STRINGS AUTO JAVA CURL)
string(TOUPPER "${MATSDK_ANDROID_HTTP_CLIENT}" MATSDK_ANDROID_HTTP_CLIENT_UPPER)
if(NOT MATSDK_ANDROID_HTTP_CLIENT_UPPER MATCHES "^(AUTO|JAVA|CURL)$")
  message(FATAL_ERROR
    "MATSDK_ANDROID_HTTP_CLIENT must be AUTO, JAVA, or CURL; got "
    "'${MATSDK_ANDROID_HTTP_CLIENT}'.")
endif()

set(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED "")
set(MATSDK_ANDROID_USES_CURL OFF)
set(MATSDK_ANDROID_USES_JAVA_HTTP OFF)
if(CMAKE_SYSTEM_NAME STREQUAL "Android")
  if(MATSDK_ANDROID_HTTP_CLIENT_UPPER STREQUAL "AUTO")
    set(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED "JAVA")
  else()
    set(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED
      "${MATSDK_ANDROID_HTTP_CLIENT_UPPER}")
  endif()

  if(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED STREQUAL "CURL")
    set(MATSDK_ANDROID_USES_CURL ON)
  else()
    set(MATSDK_ANDROID_USES_JAVA_HTTP ON)
  endif()
  message(STATUS
    "MATSDK_ANDROID_HTTP_CLIENT: ${MATSDK_ANDROID_HTTP_CLIENT} -> "
    "${MATSDK_ANDROID_HTTP_CLIENT_RESOLVED}")
endif()

option(BUILD_IOS "Deprecated: use CMAKE_SYSTEM_NAME=iOS or visionOS" OFF)
set(MATSDK_PLATFORM_IOS OFF)
if(BUILD_IOS
   OR CMAKE_SYSTEM_NAME STREQUAL "iOS"
   OR CMAKE_SYSTEM_NAME STREQUAL "visionOS")
  set(MATSDK_PLATFORM_IOS ON)
endif()

matsdk_bool_option(MATSDK_WARNINGS_AS_ERRORS ""
  "Treat warnings in SDK-owned targets as errors" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
option(LINK_STATIC_DEPENDS
  "Deprecated no-op retained for compatibility with legacy build scripts" ON)

option(BUILD_SHARED_LIBS "Build shared libraries" OFF)

set(MATSDK_SQLITE_PROVIDER "AUTO" CACHE STRING
  "SQLite dependency provider: AUTO, SYSTEM, MINIMAL, VENDORED, or NONE")
set_property(CACHE MATSDK_SQLITE_PROVIDER PROPERTY STRINGS
  AUTO SYSTEM MINIMAL VENDORED NONE)
set(MATSDK_ZLIB_PROVIDER "AUTO" CACHE STRING
  "zlib dependency provider: AUTO, SYSTEM, or VENDORED")
set_property(CACHE MATSDK_ZLIB_PROVIDER PROPERTY STRINGS AUTO SYSTEM VENDORED)

string(TOUPPER "${MATSDK_SQLITE_PROVIDER}" MATSDK_SQLITE_PROVIDER_RESOLVED)
string(TOUPPER "${MATSDK_ZLIB_PROVIDER}" MATSDK_ZLIB_PROVIDER_RESOLVED)

if(MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "AUTO")
  if(MATSDK_ANDROID_USE_ROOM AND CMAKE_SYSTEM_NAME STREQUAL "Android")
    set(MATSDK_SQLITE_PROVIDER_RESOLVED NONE)
  elseif(TARGET SQLite::SQLite3)
    set(MATSDK_SQLITE_PROVIDER_RESOLVED SYSTEM)
  elseif(NOT MATSDK_USING_VCPKG
      AND (WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Android"))
    set(MATSDK_SQLITE_PROVIDER_RESOLVED VENDORED)
  else()
    set(MATSDK_SQLITE_PROVIDER_RESOLVED SYSTEM)
  endif()
endif()

if(MATSDK_ZLIB_PROVIDER_RESOLVED STREQUAL "AUTO")
  if(TARGET ZLIB::ZLIB)
    set(MATSDK_ZLIB_PROVIDER_RESOLVED SYSTEM)
  elseif(NOT MATSDK_USING_VCPKG
      AND (WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Android"))
    set(MATSDK_ZLIB_PROVIDER_RESOLVED VENDORED)
  else()
    set(MATSDK_ZLIB_PROVIDER_RESOLVED SYSTEM)
  endif()
endif()

if(NOT MATSDK_SQLITE_PROVIDER_RESOLVED MATCHES "^(SYSTEM|MINIMAL|VENDORED|NONE)$")
  message(FATAL_ERROR
    "MATSDK_SQLITE_PROVIDER must be AUTO, SYSTEM, MINIMAL, VENDORED, or NONE; "
    "got '${MATSDK_SQLITE_PROVIDER}'.")
endif()
if(MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "NONE"
   AND NOT MATSDK_ANDROID_USE_ROOM)
  message(FATAL_ERROR
    "MATSDK_SQLITE_PROVIDER=NONE is valid only with MATSDK_ANDROID_USE_ROOM=ON.")
endif()
if(NOT MATSDK_ZLIB_PROVIDER_RESOLVED MATCHES "^(SYSTEM|VENDORED)$")
  message(FATAL_ERROR
    "MATSDK_ZLIB_PROVIDER must be AUTO, SYSTEM, or VENDORED; "
    "got '${MATSDK_ZLIB_PROVIDER}'.")
endif()
set(MATSDK_BUNDLE_SQLITE OFF)
if(MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "MINIMAL"
    OR MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "VENDORED")
  set(MATSDK_BUNDLE_SQLITE ON)
endif()
set(MATSDK_BUNDLE_ZLIB OFF)
if(MATSDK_ZLIB_PROVIDER_RESOLVED STREQUAL "VENDORED")
  set(MATSDK_BUNDLE_ZLIB ON)
endif()

message(STATUS "BUILD_SHARED_LIBS: ${BUILD_SHARED_LIBS}")
message(STATUS "MATSDK_SQLITE_PROVIDER: ${MATSDK_SQLITE_PROVIDER} -> ${MATSDK_SQLITE_PROVIDER_RESOLVED}")
message(STATUS "MATSDK_ZLIB_PROVIDER: ${MATSDK_ZLIB_PROVIDER} -> ${MATSDK_ZLIB_PROVIDER_RESOLVED}")
