include_guard()

function(matsdk_namespace_sqlite target header output)
  set(symbols)
  # The amalgamations also declare platform APIs and test globals absent from sqlite3.h.
  foreach(source IN ITEMS "${header}" ${ARGN})
    file(STRINGS "${source}" declarations REGEX "^SQLITE_API ")
    foreach(declaration IN LISTS declarations)
      string(REGEX MATCH "sqlite3[A-Za-z0-9_]+[ \t]*[()\\[;=]" symbol "${declaration}")
      if(NOT symbol)
        message(FATAL_ERROR "Cannot namespace SQLite API declaration: ${declaration}")
      endif()
      string(REGEX REPLACE "[ \t]*[()\\[;=]$" "" symbol "${symbol}")
      list(APPEND symbols "${symbol}")
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  endforeach()
  if(NOT symbols)
    message(FATAL_ERROR "No SQLite API declarations found in ${header}")
  endif()
  list(REMOVE_DUPLICATES symbols)
  list(SORT symbols)
  set(contents "#pragma once\n")
  foreach(symbol IN LISTS symbols)
    string(APPEND contents "#define ${symbol} matsdk_${symbol}\n")
  endforeach()
  file(GENERATE OUTPUT "${output}" CONTENT "${contents}")
  if(MSVC)
    target_compile_options(${target} INTERFACE "/FI${output}")
  else()
    target_compile_options(${target} INTERFACE "SHELL:-include \"${output}\"")
  endif()
endfunction()
