if(DEFINED PROJECT_IS_TOP_LEVEL)
  set(MATSDK_PROJECT_IS_TOP_LEVEL "${PROJECT_IS_TOP_LEVEL}")
elseif(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  set(MATSDK_PROJECT_IS_TOP_LEVEL ON)
else()
  set(MATSDK_PROJECT_IS_TOP_LEVEL OFF)
endif()

option(MATSDK_BUILD_HEADERS
  "Build API headers" ON)
option(MATSDK_BUILD_LIBRARY
  "Build the SDK library" ON)
option(MATSDK_BUILD_TEST_TOOL
  "Build the console test tool" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
option(MATSDK_BUILD_UNIT_TESTS
  "Build unit tests" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
option(MATSDK_BUILD_FUNC_TESTS
  "Build functional tests" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
option(MATSDK_BUILD_JNI_WRAPPER
  "Build the JNI wrapper" OFF)
option(MATSDK_ANDROID_USE_ROOM
  "Use Android Room for offline storage" OFF)
option(MATSDK_ENABLE_CAPI_HTTP_CLIENT
  "Enable the C API HTTP client on Android" OFF)
option(MATSDK_BUILD_OBJC_WRAPPER
  "Build the Objective-C wrapper" ON)
option(MATSDK_BUILD_SWIFT_WRAPPER
  "Build Swift wrappers" ON)
option(MATSDK_BUILD_PACKAGE
  "Build an SDK package" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
option(MATSDK_BUILD_PRIVACYGUARD
  "Build Privacy Guard" ON)
option(MATSDK_BUILD_CDS
  "Build Common Diagnostic Stack" ON)
option(MATSDK_BUILD_LIVEEVENTINSPECTOR
  "Build Live Event Inspector" ON)
option(MATSDK_BUILD_SIGNALS
  "Build Signals" ON)
option(MATSDK_BUILD_SANITIZER
  "Build Sanitizer" ON)
option(MATSDK_BUILD_AZMON
  "Build Azure Monitor / Application Insights support" ON)
option(MATSDK_BUILD_APPLE_HTTP
  "Build the Apple-native HTTP client" "${APPLE}")

set(_matsdk_android_http_client_predefined OFF)
if(DEFINED MATSDK_ANDROID_HTTP_CLIENT)
  set(_matsdk_android_http_client_predefined ON)
endif()
set(MATSDK_ANDROID_HTTP_CLIENT "AUTO" CACHE STRING
  "Android HTTP client: AUTO, JAVA, or CURL")
set_property(CACHE MATSDK_ANDROID_HTTP_CLIENT PROPERTY STRINGS AUTO JAVA CURL)

# Legacy alias: USE_CURL=ON selected the native curl transport on Android
# before MATSDK_ANDROID_HTTP_CLIENT existed. Translate it (once, unless the
# canonical option was already set explicitly) rather than dropping it, since
# it is a real behavioral switch for deliberate Android curl consumers, not
# just a renamed knob.
if(DEFINED USE_CURL AND USE_CURL)
  if(_matsdk_android_http_client_predefined
     AND NOT MATSDK_ANDROID_HTTP_CLIENT STREQUAL "CURL")
    message(DEPRECATION
      "USE_CURL is deprecated and conflicts with MATSDK_ANDROID_HTTP_CLIENT; "
      "MATSDK_ANDROID_HTTP_CLIENT=${MATSDK_ANDROID_HTTP_CLIENT} takes precedence.")
  elseif(NOT _matsdk_android_http_client_predefined)
    set(MATSDK_ANDROID_HTTP_CLIENT "CURL" CACHE STRING
      "Android HTTP client: AUTO, JAVA, or CURL" FORCE)
  endif()
endif()

string(TOUPPER "${MATSDK_ANDROID_HTTP_CLIENT}" MATSDK_ANDROID_HTTP_CLIENT_UPPER)
if(NOT MATSDK_ANDROID_HTTP_CLIENT_UPPER MATCHES "^(AUTO|JAVA|CURL)$")
  message(FATAL_ERROR
    "MATSDK_ANDROID_HTTP_CLIENT must be AUTO, JAVA, or CURL; got "
    "'${MATSDK_ANDROID_HTTP_CLIENT}'.")
endif()

set(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED "")
set(MATSDK_ANDROID_USES_CURL OFF)
set(MATSDK_ANDROID_USES_JAVA_HTTP OFF)
if(CMAKE_SYSTEM_NAME STREQUAL "Android")
  if(MATSDK_ANDROID_HTTP_CLIENT_UPPER STREQUAL "AUTO")
    set(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED "JAVA")
  else()
    set(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED
      "${MATSDK_ANDROID_HTTP_CLIENT_UPPER}")
  endif()

  if(MATSDK_ANDROID_HTTP_CLIENT_RESOLVED STREQUAL "CURL")
    set(MATSDK_ANDROID_USES_CURL ON)
  else()
    set(MATSDK_ANDROID_USES_JAVA_HTTP ON)
  endif()
  message(STATUS
    "MATSDK_ANDROID_HTTP_CLIENT: ${MATSDK_ANDROID_HTTP_CLIENT} -> "
    "${MATSDK_ANDROID_HTTP_CLIENT_RESOLVED}")
endif()

option(BUILD_IOS "Deprecated: use CMAKE_SYSTEM_NAME=iOS or visionOS" OFF)
set(MATSDK_PLATFORM_IOS OFF)
if(BUILD_IOS
   OR CMAKE_SYSTEM_NAME STREQUAL "iOS"
   OR CMAKE_SYSTEM_NAME STREQUAL "visionOS")
  set(MATSDK_PLATFORM_IOS ON)
endif()

option(MATSDK_WARNINGS_AS_ERRORS
  "Treat warnings in SDK-owned targets as errors" "${MATSDK_PROJECT_IS_TOP_LEVEL}")
option(LINK_STATIC_DEPENDS
  "Deprecated no-op retained for compatibility with legacy build scripts" ON)

option(BUILD_SHARED_LIBS "Build shared libraries" OFF)

set(MATSDK_SQLITE_PROVIDER "AUTO" CACHE STRING
  "SQLite dependency provider: AUTO, SYSTEM, MINIMAL, VENDORED, or NONE")
set_property(CACHE MATSDK_SQLITE_PROVIDER PROPERTY STRINGS
  AUTO SYSTEM MINIMAL VENDORED NONE)
set(MATSDK_ZLIB_PROVIDER "AUTO" CACHE STRING
  "zlib dependency provider: AUTO, SYSTEM, or VENDORED")
set_property(CACHE MATSDK_ZLIB_PROVIDER PROPERTY STRINGS AUTO SYSTEM VENDORED)

string(TOUPPER "${MATSDK_SQLITE_PROVIDER}" MATSDK_SQLITE_PROVIDER_RESOLVED)
string(TOUPPER "${MATSDK_ZLIB_PROVIDER}" MATSDK_ZLIB_PROVIDER_RESOLVED)

if(MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "AUTO")
  if(MATSDK_ANDROID_USE_ROOM AND CMAKE_SYSTEM_NAME STREQUAL "Android")
    set(MATSDK_SQLITE_PROVIDER_RESOLVED NONE)
  elseif(TARGET SQLite::SQLite3 OR TARGET SQLite3::SQLite3)
    set(MATSDK_SQLITE_PROVIDER_RESOLVED SYSTEM)
  elseif(NOT MATSDK_USING_VCPKG
      AND (WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Android"))
    set(MATSDK_SQLITE_PROVIDER_RESOLVED VENDORED)
  else()
    set(MATSDK_SQLITE_PROVIDER_RESOLVED SYSTEM)
  endif()
endif()

if(MATSDK_ZLIB_PROVIDER_RESOLVED STREQUAL "AUTO")
  if(TARGET ZLIB::ZLIB)
    set(MATSDK_ZLIB_PROVIDER_RESOLVED SYSTEM)
  elseif(NOT MATSDK_USING_VCPKG
      AND (WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Android"))
    set(MATSDK_ZLIB_PROVIDER_RESOLVED VENDORED)
  else()
    set(MATSDK_ZLIB_PROVIDER_RESOLVED SYSTEM)
  endif()
endif()

if(MATSDK_ANDROID_USE_ROOM AND NOT CMAKE_SYSTEM_NAME STREQUAL "Android")
  message(FATAL_ERROR
    "MATSDK_ANDROID_USE_ROOM is supported only when CMAKE_SYSTEM_NAME is Android.")
endif()

if(NOT MATSDK_SQLITE_PROVIDER_RESOLVED MATCHES "^(SYSTEM|MINIMAL|VENDORED|NONE)$")
  message(FATAL_ERROR
    "MATSDK_SQLITE_PROVIDER must be AUTO, SYSTEM, MINIMAL, VENDORED, or NONE; "
    "got '${MATSDK_SQLITE_PROVIDER}'.")
endif()
if(MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "NONE"
   AND NOT MATSDK_ANDROID_USE_ROOM)
  message(FATAL_ERROR
    "MATSDK_SQLITE_PROVIDER=NONE is valid only with MATSDK_ANDROID_USE_ROOM=ON.")
endif()
if(NOT MATSDK_ZLIB_PROVIDER_RESOLVED MATCHES "^(SYSTEM|VENDORED)$")
  message(FATAL_ERROR
    "MATSDK_ZLIB_PROVIDER must be AUTO, SYSTEM, or VENDORED; "
    "got '${MATSDK_ZLIB_PROVIDER}'.")
endif()
set(MATSDK_BUNDLE_SQLITE OFF)
if(MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "MINIMAL"
    OR MATSDK_SQLITE_PROVIDER_RESOLVED STREQUAL "VENDORED")
  set(MATSDK_BUNDLE_SQLITE ON)
endif()
set(MATSDK_BUNDLE_ZLIB OFF)
if(MATSDK_ZLIB_PROVIDER_RESOLVED STREQUAL "VENDORED")
  set(MATSDK_BUNDLE_ZLIB ON)
endif()

message(STATUS "BUILD_SHARED_LIBS: ${BUILD_SHARED_LIBS}")
message(STATUS "MATSDK_SQLITE_PROVIDER: ${MATSDK_SQLITE_PROVIDER} -> ${MATSDK_SQLITE_PROVIDER_RESOLVED}")
message(STATUS "MATSDK_ZLIB_PROVIDER: ${MATSDK_ZLIB_PROVIDER} -> ${MATSDK_ZLIB_PROVIDER_RESOLVED}")
