name: Build for Xamarin

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ios:
    name: Build for iOS
    runs-on: macOS-latest
    strategy:
        matrix:
            arch: ["arm64", "arm64e", "x86_64"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        token:  ${{ secrets.GIT_PULL_TOKEN }}
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PULL_TOKEN: ${{ secrets.GIT_PULL_TOKEN }}
      run: ./build-ios.sh release ${{ matrix.arch }}

  build-android:
    runs-on: windows-latest
    name: Build for Android
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        token:  ${{ secrets.GIT_PULL_TOKEN }}
    - name: Chocolatey
      run: |
        $Env:ANDROID_SDK_ROOT = "C:\Android\android-sdk"
        gci env:* | sort-object name
        choco install --no-progress -y android-sdk
        choco install --no-progress -y ninja
        new-item "C:\Users\runneradmin\.android\repositories.cfg" -ItemType "file"
        echo yes | C:\Android\android-sdk\tools\bin\sdkmanager.bat "ndk-bundle" "cmake;3.10.2.4988404" "ndk;20.0.5594570" --sdk_root=$Env:ANDROID_SDK_ROOT
        gci -r -i "CMake*" C:\Android
        echo $Env:PATH
    - name: Gradle Build
      run: |
        $Env:PATH = "C:\Android\android-sdk\cmake\3.10.2.4988404\bin;" + $Env:PATH
        cd "$Env:GITHUB_WORKSPACE\lib\android_build"
        .\gradlew.bat assemble
      env:
        ANDROID_SDK_ROOT: "C:\\Android\\android-sdk"
        ANDROID_HOME: "C:\\Android\\android-sdk"
        ANDROID_NDK: "C:\\Android\\android-ndk-r20"
        ANDROID_NDK_HOME: "C:\\Android\\android-ndk-r20"
