name: C/C++ CI on Windows (vs2022)

on:
  push:
    branches:
    - master
    - main
    - dev

  pull_request:
    branches:
    - master
    - main
    - dev

jobs:
  build:

    runs-on: windows-2022
    name: Build

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      continue-on-error: true

    - name: Build
      env:
        SKIP_ARM_BUILD: 1
        SKIP_ARM64_BUILD: 1
        PlatformToolset: v143
        VSTOOLS_VERSION: vs2022
      shell: cmd
      run: build-all.bat
