name: C/C++ CI on Windows (clang)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    name: Build for Windows (clang)

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Tools
      shell: cmd
      run: tools\install-vs-addons.cmd
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PULL_TOKEN: ${{ secrets.GIT_PULL_TOKEN }}
      shell: cmd
      run: build-all.bat
