name: Build and Run Unit/Functional tests on Windows

on:
  push:
    branches:
    - master
    - main
    - dev
    - dev/*
    - release/*
    - buildme/*

  pull_request:
    branches:
    - master
    - main
    - dev

  schedule:
  - cron: 0 2 * * 1-5


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: Test on Windows ${{ matrix.arch }}-${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [Win32, x64]
        build: [Release, Debug]
        os: [windows-2022]
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      continue-on-error: true

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17,)'

    - name: Test ${{ matrix.arch }} ${{ matrix.build }}
      shell: cmd
      run: build-tests.cmd ${{ matrix.arch }} ${{ matrix.build }}
